### ISSUE TITLE
jekyll themes

### ISSUE THREAD

**Issue by evanwill** [uidaholib/palouse-digital#2]
- [minimal-mistakes](https://github.com/mmistakes/minimal-mistakes)
- [Feeling Responsive](https://github.com/Phlow/feeling-responsive/tree/gh-pages)
- [Creative Theme](http://themes.jekyllrc.org/creative-theme/)
- [Agency](http://themes.jekyllrc.org/agency/)

**Comment by dcnb** [comment]
I was actually setting up a minimal mistakes yesterday afternoon. My work
computer of course wasn't working though. I have it on my home computer
now, and am looking at it. It's kind of complicated overall, but it looks
really good.

I've got a little bit going. Do you want me to add it as a /docs folder to
palouse digital?

**Comment by evanwill** [comment]
looks good!
but yeah, the theme is over complicated for what it does, and organized oddly.
